### ISSUE TITLE
resuming tag finder on a saved state with tag ambiguities and without "-e" flag segfaults

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/find_tags#7]
This might not matter since we will always(?) be running with the "-e"  (= --use_events) flag.
Still, in case it turns out we have problems when resuming in the presence of 
large tagAmbig tables, here's an example

e.g. with file: AVFP-3214BBBK1004-000118-2016-05-25T07-05-24.9250T-all.txt.gz

this code:

``` shell
DIR=/SG/contrib/2016/Niles/Reeds/filed/2016-05-25
F=$DIR/AVFP-3214BBBK1004-000118-2016-05-25T07-05-24.9250T-all.txt
FF=/tmp/`basename $F`
zcat $F.gz | head -4000l > $FF
Rscript -e "{library(motus); sgRunNewFiles('$FF', '/tmp', par='-c 8 -s 0.5 -m 0 -M 12 -C 30 -S 200 -f 166.38')}"
zcat $F.gz > $FF
Rscript -e "{library(motus); sgRunNewFiles('$FF', '/tmp', par='-c 8 -s 0.5 -m 0 -M 12 -C 30 -S 200 -f 166.38')}"
```

segfaults.  The detailed backtrace:

```
gdb find_tags_motus
...
Reading symbols from /raid5tb/john/proj/find_tags/find_tags_motus...done.
(gdb) run  -c 8 -s 0.5 -m 0 -M 12 -C 30 -S 200 -f 166.38 --resume --bootnum=118 --src_sqlite /sgm/cached_motus_meta_db.sqlite /tmp/SG-3214BBBK1004.motus
Starting program: /raid5tb/john/proj/find_tags/find_tags_motus -c 8 -s 0.5 -m 0 -M 12 -C 30 -S 200 -f 166.38 --resume --bootnum=118 --src_sqlite /sgm/cached_motus_meta_db.sqlite /tmp/SG-3214BBBK1004.motus
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7242540 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7242540 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000412d8e in operator++ (this=<synthetic pointer>) at /usr/include/c++/4.7/bits/stl_tree.h:277
Python Exception <type 'exceptions.IndexError'> list index out of range: 
#2  DB_Filer::save_ambiguity (this=0x7fffffffdef0, proxyID=<optimized out>, tags=std::set with 0 elements) at DB_Filer.cpp:448
#3  0x000000000042406f in Tag_Candidate::dump_bursts (this=0x1a6ac80, prefix="2,") at Tag_Candidate.cpp:299
#4  0x0000000000428588 in Tag_Finder::process (this=0x1ec70e0, p=...) at Tag_Finder.cpp:100
#5  0x000000000042aab5 in Tag_Foray::start (this=0x7fffffffdfc0) at Tag_Foray.cpp:176
#6  0x000000000040acd1 in main (argc=<optimized out>, argv=0x7fffffffe358) at find_tags_motus.cpp:656
(gdb) frame 2
Python Exception <type 'exceptions.IndexError'> list index out of range: 
#2  DB_Filer::save_ambiguity (this=0x7fffffffdef0, proxyID=<optimized out>, tags=std::set with 0 elements) at DB_Filer.cpp:448
448       sqlite3_bind_int( st_save_ambig, 1 + i, (*t++) -> motusID);
(gdb) p t
$1 = Cannot access memory at address 0x20
```

**Comment by jbrzusto** [comment]
This no longer appears to be the case, but we don't have the original saved state to test against.
It's possible the state was invalidated by a change in serialization format, even at the time
of the report, so I'm closing this.
